name: 'Github Rubocop Action'
description: 'Runs rubocop on your PRs :)'
author: 'Stéphane FEUGA OSHIMA'
branding:
  icon: 'alert-triangle'
  color: 'red'
runs:
  using: 'docker'
  image: 'Dockerfile'
